export const themes = {
  sunriseMeadow: { name: 'Sunrise Meadow', type: 'light' },
  coastalBreeze: { name: 'Coastal Breeze', type: 'light' },
  citrusPop: { name: 'Citrus Pop', type: 'light' },
  coralBloom: { name: 'Coral Bloom', type: 'light' },
  skywash: { name: 'Skywash', type: 'light' },
  pastelField: { name: 'Pastel Field', type: 'light' },
  canyonGlow: { name: 'Canyon Glow', type: 'light' },
  tropicalInk: { name: 'Tropical Ink', type: 'light' },
  summerGrain: { name: 'Summer Grain', type: 'light' },
  auroraDaylight: { name: 'Aurora Daylight', type: 'light' },
  deepSpace: { name: 'Deep Space', type: 'dark' },
  nebulaVeil: { name: 'Nebula Veil', type: 'dark' },
  solarEclipse: { name: 'Solar Eclipse', type: 'dark' },
  eventHorizon: { name: 'Event Horizon', type: 'dark' },
  midnightAurora: { name: 'Midnight Aurora', type: 'dark' },
  starfieldGlass: { name: 'Starfield Glass', type: 'dark' },
  galaxyDust: { name: 'Galaxy Dust', type: 'dark' },
  lunarSurface: { name: 'Lunar Surface', type: 'dark' },
  cometTrail: { name: 'Comet Trail', type: 'dark' },
  voidGradient: { name: 'Void Gradient', type: 'dark' },
};